### ISSUE TITLE
CLI Master issue

### ISSUE THREAD

**Issue by TomAugspurger** [TomAugspurger/stitch#6]
What options are there (and which will we support)

- [ ] filters
- [ ] define default `extra_args` and gracefully merge / override those
- [ ] debug
- [ ] infer `to` (export format) from extension like pandoc
- [ ] Collections of documents? (clean state between?)
- [ ]
